# Generated by Django 2.0.10 on 2019-02-19 01:43

from django.db import migrations, models
import kbspre.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190216_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playername',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AddField(
            model_name='comment',
            name='step',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AddField(
            model_name='comment',
            name='survey',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AddField(
            model_name='comment',
            name='tel',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
    ]
