# Generated by Django 2.0.10 on 2019-02-19 01:43

from django.db import migrations, models
import kbspre.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20190219_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mail',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.TextField(null=True, verbose_name=kbspre.users.models.User),
        ),
    ]
