# Generated by Django 2.0.10 on 2019-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20190219_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='mail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='playername',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='survey',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tel',
            field=models.TextField(null=True),
        ),
    ]
